Repository depromeet12th/three-days-android, pull requests merged in 2022-12, with the labels that each got.

#52 DEP-170 짝꿍 만들기 1단계 UI 구현
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/ConnectHabitFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/ConnectHabitViewModel.kt
  presentation/mate/src/main/res/layout/fragment_connect_habit.xml
  presentation/mate/src/main/res/layout/item_habit.xml
  presentation/mate/src/main/res/values/strings.xml
Labels: enhancement

#51 DEP-168 습관 삭제, 수정 모달 ui 변경
  core-design-system/src/main/res/drawable/ic_delete.xml
  core-design-system/src/main/res/drawable/ic_edit.xml
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/MoreActionModal.kt
  presentation/home/src/main/res/layout/modal_edit_habit.xml
  presentation/home/src/main/res/values/strings.xml
Labels: enhancement

#49 DEP-145 ui: 상태에 따라 체크 ui를 변경하는 화면 구현
  core-design-system/src/main/res/drawable/bg_rect_main_r30.xml
  core-design-system/src/main/res/drawable/ic_check_pressed.xml
  core-design-system/src/main/res/drawable/ic_hand_done.png
  core-design-system/src/main/res/drawable/ic_hand_normal.png
  core-design-system/src/main/res/drawable/img_hand_01.png
  core-design-system/src/main/res/values/colors.xml
  core-design-system/src/main/res/values/typography.xml
  core/src/main/java/com/depromeet/threedays/core/extensions/View.kt
  data/src/main/java/com/depromeet/threedays/data/mapper/HabitMapper.kt
  domain/src/main/java/com/depromeet/threedays/domain/entity/Color.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/DeleteHabitDialog.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HabitAdapter.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HabitViewHolder.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeViewModel.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/MoreActionModal.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/model/HabitUI.kt
  presentation/home/src/main/res/drawable/bg_oval_blue.xml
  presentation/home/src/main/res/drawable/bg_oval_blue_pressed.xml
  presentation/home/src/main/res/drawable/bg_oval_gray_stroke_blue.xml
  presentation/home/src/main/res/drawable/bg_oval_green.xml
  presentation/home/src/main/res/drawable/bg_oval_green_pressed.xml
  presentation/home/src/main/res/drawable/bg_oval_light_blue.xml
  presentation/home/src/main/res/drawable/bg_oval_light_blue_pressed.xml
  presentation/home/src/main/res/drawable/bg_oval_light_green.xml
  presentation/home/src/main/res/drawable/bg_oval_light_green_pressed.xml
  presentation/home/src/main/res/drawable/bg_oval_light_pink.xml
  presentation/home/src/main/res/drawable/bg_oval_light_pink_pressed.xml
  presentation/home/src/main/res/drawable/bg_oval_pink.xml
  presentation/home/src/main/res/drawable/bg_oval_pink_pressed.xml
  presentation/home/src/main/res/drawable/bg_oval_stroke_blue.xml
  presentation/home/src/main/res/drawable/ic_noti_active.xml
  presentation/home/src/main/res/drawable/ic_noti_default.xml
  presentation/home/src/main/res/drawable/ic_noti_off.xml
  presentation/home/src/main/res/drawable/selector_check.xml
  presentation/home/src/main/res/drawable/selector_check_blue.xml
  presentation/home/src/main/res/drawable/selector_check_green.xml
  presentation/home/src/main/res/drawable/selector_check_light_blue.xml
  presentation/home/src/main/res/drawable/selector_check_light_green.xml
  presentation/home/src/main/res/drawable/selector_check_light_pink.xml
  presentation/home/src/main/res/drawable/selector_check_pink.xml
  presentation/home/src/main/res/layout/activity_main.xml
  presentation/home/src/main/res/layout/fragment_home.xml
  presentation/home/src/main/res/layout/item_habit.xml
Labels: enhancement

#54 DEP-170 ui: 그라데이션 추가
  presentation/mate/src/main/res/drawable/bg_white_gradient.xml
  presentation/mate/src/main/res/layout/fragment_connect_habit.xml
Labels: enhancement

#57 DEP-187 ui: 짝꿍 만들기 3단계 UI 구현
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameViewMoodel.kt
  presentation/mate/src/main/res/drawable/bg_rect_gray100_border_gray300_r10.xml
  presentation/mate/src/main/res/drawable/selector_edittext.xml
  presentation/mate/src/main/res/layout/fragment_set_mate_nickname.xml
  presentation/mate/src/main/res/values/strings.xml
Labels: enhancement

#58 DEP-186 ui: 짝꿍 선택에 따라 효과 추가
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step2/ChooseMateTypeFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step2/ChooseMateTypeViewModel.kt
  presentation/mate/src/main/res/drawable/bg_rect_gray_200_border_gray_400_r10.xml
  presentation/mate/src/main/res/layout/fragment_choose_mate_type.xml
Labels: enhancement

#63 DEP-194 ui: 짝꿍 페이지 툴팁과 디폴트 화면 구현
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
  presentation/mate/src/main/res/layout/fragment_mate.xml
  presentation/mate/src/main/res/values/strings.xml
Labels: enhancement

#66 DEP-200 ui: 짝꿍 온보딩 ui 구현
  core-design-system/src/main/res/drawable/bg_rect_white_top_r20.xml
  core-design-system/src/main/res/values/themes.xml
  presentation/create/src/main/java/com/depromeet/threedays/create/emoji/EmojiBottomSheetDialogFragment.kt
  presentation/home/src/main/res/values/themes.xml
  presentation/mate/src/main/java/com/depromeet/threedays/mate/onboarding/OnBoardingAdapter.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/onboarding/OnBoardingBottomSheet.kt
  presentation/mate/src/main/res/drawable/bg_oval_gray_300_default_dot.xml
  presentation/mate/src/main/res/drawable/bg_oval_gray_600_selected_dot.xml
  presentation/mate/src/main/res/layout/bottom_sheet_mate_on_boarding.xml
  presentation/mate/src/main/res/layout/item_on_boarding_mate.xml
  presentation/mate/src/main/res/values/strings.xml
Labels: enhancement

#67 DEP-201 ui: 공유하기 페이지 UI 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  core-design-system/src/main/res/drawable/bg_rect_gray800_r8.xml
  core-design-system/src/main/res/drawable/ic_image_save.xml
  core-design-system/src/main/res/drawable/ic_instagram_share.png
  core-design-system/src/main/res/drawable/ic_instagram_share_resized.xml
  core-design-system/src/main/res/drawable/ic_logo_white.xml
  presentation/mate/src/main/AndroidManifest.xml
  presentation/mate/src/main/java/com/depromeet/threedays/mate/share/ShareMateActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/share/ShareMateViewModel.kt
  presentation/mate/src/main/res/layout/activity_share_mate.xml
  presentation/mate/src/main/res/values/strings.xml
Labels: enhancement

#68 DEP-202 ui: 최종 레벨 달성
  core-design-system/src/main/res/drawable/ic_popup_close.xml
  core-design-system/src/main/res/drawable/ic_popup_close_pressed.xml
  core-design-system/src/main/res/drawable/selector_popup_close.xml
  core/src/main/java/com/depromeet/threedays/core/util/ThreeDaysNoButtonDialogFragment.kt
  core/src/main/res/layout/fragment_three_days_no_button_dialog.xml
  presentation/mate/src/main/res/values/strings.xml
Labels: enhancement

#69 DEP-148 ui: 나의 기록 ui 변경 사항 적용
  core-design-system/src/main/res/drawable/ic_check_small.xml
  presentation/history/src/main/res/layout/fragment_history.xml
Labels: enhancement

#74 DEP-206 ui: 알림 권유 바텀시트 구현
  presentation/home/src/main/java/com/depromeet/threedays/home/home/NotiRecommendBottomSheet.kt
  presentation/home/src/main/res/drawable/bg_noti_recommend_box.png
  presentation/home/src/main/res/layout/bottom_sheet_noti_recommend.xml
  presentation/home/src/main/res/values/strings.xml
Labels: enhancement

#72 DEP-205 ui: 짝꿍 페이지 리뉴얼
  core-design-system/src/main/res/drawable/bg_rect_green50_r10.xml
  core-design-system/src/main/res/drawable/bg_rect_white_r15.xml
  core-design-system/src/main/res/values/typography.xml
  presentation/mate/src/main/java/com/depromeet/threedays/mate/nomate/NoMateFragment.kt
  presentation/mate/src/main/res/drawable/ic_polygon.xml
  presentation/mate/src/main/res/layout/fragment_mate.xml
  presentation/mate/src/main/res/layout/fragment_no_mate.xml
  presentation/mate/src/main/res/values/strings.xml
Labels: enhancement

#73 DEP-198 마이페이지 ui 적용
  .idea/compiler.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle
  core-design-system/build.gradle
  core-design-system/src/main/res/drawable/bg_oval_gray200.xml
  core-design-system/src/main/res/drawable/bg_rect_main_r10.xml
  core-design-system/src/main/res/drawable/bg_rect_white_r10_border_gray450.xml
  core-design-system/src/main/res/drawable/bg_rect_white_r20.xml
  core-design-system/src/main/res/drawable/ic_close_white.xml
  core-design-system/src/main/res/drawable/ic_edit_gray450.xml
  core-design-system/src/main/res/drawable/selector_switch_button_track.xml
  core-design-system/src/main/res/drawable/shape_switch_thumb.xml
  core-design-system/src/main/res/drawable/shape_switch_track_off.xml
  core-design-system/src/main/res/drawable/shape_switch_track_on.xml
  core/build.gradle
  data/src/main/java/com/depromeet/threedays/data/api/HabitService.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/habit/HabitRemoteDataSource.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/habit/HabitRemoteDataSourceImpl.kt
  data/src/main/java/com/depromeet/threedays/data/entity/HabitEntity.kt
  data/src/main/java/com/depromeet/threedays/data/repository/HabitRepositoryImpl.kt
  domain/src/main/java/com/depromeet/threedays/domain/entity/habit/Habit.kt
  domain/src/main/java/com/depromeet/threedays/domain/repository/HabitRepository.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/GetArchivedHabitsUseCase.kt
  navigator/build.gradle
  navigator/src/main/java/com/depromeet/threedays/navigator/ArchivedHabitNavigator.kt
  presentation/history/build.gradle
  presentation/home/build.gradle
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HabitViewHolder.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/model/HabitUI.kt
  presentation/mate/build.gradle
  presentation/mypage/build.gradle
  presentation/mypage/src/main/AndroidManifest.xml
  presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageFragment.kt
  presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageModule.kt
  presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitActivity.kt
  presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitAdapter.kt
  presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitNavigatorImpl.kt
  presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitOnboardingSnackBar.kt
  presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitUI.kt
  presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitViewHolder.kt
  presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitViewModel.kt
  presentation/mypage/src/main/java/com/depromeet/threedays/mypage/nickname/EditNicknameDialogFragment.kt
  presentation/mypage/src/main/res/layout/activity_archived_habit.xml
  presentation/mypage/src/main/res/layout/fragment_edit_nickname_dialog.xml
  presentation/mypage/src/main/res/layout/fragment_my_page.xml
  presentation/mypage/src/main/res/layout/item_habit_archived.xml
  presentation/mypage/src/main/res/layout/snackbar_archived_habit_onboarding.xml
  presentation/mypage/src/main/res/values/strings.xml
  presentation/notification/src/main/java/com/depromeet/threedays/notification/NotificationActivity.kt
Labels: enhancement

#70 DEP-195 ui: 이미지가 있는 스낵바 구현
  core/src/main/java/com/depromeet/threedays/core/util/ThreeDaysImageSnackBar.kt
  core/src/main/res/layout/image_snackbar_three_days.xml
Labels: enhancement

#53 DEP-175 feat: 습관 삭제 기능 구현
  data/src/main/java/com/depromeet/threedays/data/api/HabitService.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/habit/HabitRemoteDataSource.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/habit/HabitRemoteDataSourceImpl.kt
  data/src/main/java/com/depromeet/threedays/data/repository/HabitRepositoryImpl.kt
  domain/src/main/java/com/depromeet/threedays/domain/repository/HabitRepository.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/DeleteHabitUseCase.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeViewModel.kt
  presentation/home/src/main/res/values/strings.xml
Labels: enhancement

#86 DEP-214 feat: 짝꿍 만들기 / 기본 화면 -> 1단계 -> 2단계 기능 구현
  app/src/main/AndroidManifest.xml
  data/src/main/java/com/depromeet/threedays/data/api/HabitService.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/habit/HabitRemoteDataSource.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/habit/HabitRemoteDataSourceImpl.kt
  data/src/main/java/com/depromeet/threedays/data/repository/HabitRepositoryImpl.kt
  domain/src/main/java/com/depromeet/threedays/domain/entity/HabitStatus.kt
  domain/src/main/java/com/depromeet/threedays/domain/repository/HabitRepository.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/GetHabitUseCase.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/habit/GetActiveHabitsUseCase.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/habit/GetArchivedHabitsUseCase.kt
  navigator/src/main/java/com/depromeet/threedays/navigator/ConnectHabitNavigator.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/MainActivity.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeViewModel.kt
  presentation/mate/src/main/AndroidManifest.xml
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitAdapter.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitModule.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitNavigatorImpl.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitViewHolder.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitViewModel.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/model/HabitUI.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step2/ChooseMateTypeActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step2/ChooseMateTypeFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/nomate/NoMateFragment.kt
  presentation/mate/src/main/res/drawable/bg_help_mate_image.xml
  presentation/mate/src/main/res/layout/activity_choose_mate_type.xml
  presentation/mate/src/main/res/layout/activity_connect_habit.xml
  presentation/mate/src/main/res/layout/fragment_no_mate.xml
  presentation/mate/src/main/res/layout/item_connect_habit.xml
Labels: enhancement

#90 DEP-214 feat: 짝꿍 만들기 2단계, 3단계 기능 구현
  app/src/main/AndroidManifest.xml
  data/src/main/java/com/depromeet/threedays/data/api/MateService.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/mate/MateRemoteDataSource.kt
  data/src/main/java/com/depromeet/threedays/data/entity/RewardHistory.kt
  data/src/main/java/com/depromeet/threedays/data/entity/mate/MateEntity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step2/ChooseMateTypeActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step2/ChooseMateTypeViewModel.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameViewMoodel.kt
  presentation/mate/src/main/res/drawable/ic_carrot_mate_selected.xml
  presentation/mate/src/main/res/drawable/ic_carrot_mate_unselected.xml
  presentation/mate/src/main/res/drawable/ic_whipping_mate_selected.xml
  presentation/mate/src/main/res/drawable/ic_whipping_mate_unselected.xml
  presentation/mate/src/main/res/layout/activity_choose_mate_type.xml
  presentation/mate/src/main/res/layout/activity_set_mate_nickname.xml
  presentation/mate/src/main/res/values/strings.xml
Labels: enhancement

#99 DEP-265 feat: 짝꿍 api 구현과 연동
  data/src/main/java/com/depromeet/threedays/data/api/MateService.kt
  data/src/main/java/com/depromeet/threedays/data/api/deserializer/MateTypeDeserializer.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/mate/MateRemoteDataSource.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/mate/MateRemoteDataSourceImpl.kt
  data/src/main/java/com/depromeet/threedays/data/di/RemoteModule.kt
  data/src/main/java/com/depromeet/threedays/data/di/RepositoryModule.kt
  data/src/main/java/com/depromeet/threedays/data/di/ServiceModule.kt
  data/src/main/java/com/depromeet/threedays/data/entity/mate/MateEntity.kt
  data/src/main/java/com/depromeet/threedays/data/mapper/MateMapper.kt
  data/src/main/java/com/depromeet/threedays/data/repository/MateRepositoryImpl.kt
  domain/src/main/java/com/depromeet/threedays/domain/entity/mate/Mate.kt
  domain/src/main/java/com/depromeet/threedays/domain/entity/mate/MateType.kt
  domain/src/main/java/com/depromeet/threedays/domain/repository/MateRepository.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/mate/GetMatesUseCase.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/MainActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateViewModel.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/model/MateUI.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/nomate/NoMateFragment.kt
  presentation/mate/src/main/res/layout/fragment_mate.xml
  presentation/mate/src/main/res/layout/fragment_no_mate.xml
  presentation/mate/src/main/res/values/strings.xml
Labels: enhancement

#107 DEP-258 feat: 습관 성취, 삭제 api 연동 + 리스트 맨 마지막 습관 만들기 기능 구현
  data/src/main/java/com/depromeet/threedays/data/api/AchievementService.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/achievement/AchievementRemoteDataSource.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/achievement/AchievementRemoteDataSourceImpl.kt
  data/src/main/java/com/depromeet/threedays/data/entity/achievement/AchievementDateEntity.kt
  data/src/main/java/com/depromeet/threedays/data/entity/mate/MateEntity.kt
  data/src/main/java/com/depromeet/threedays/data/mapper/MateMapper.kt
  data/src/main/java/com/depromeet/threedays/data/repository/AchievementRepositoryImpl.kt
  domain/src/main/java/com/depromeet/threedays/domain/entity/mate/Mate.kt
  domain/src/main/java/com/depromeet/threedays/domain/repository/AchievementRepository.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/achievement/CreateHabitAchievementUseCase.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/achievement/DeleteHabitAchievementUseCase.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HabitAdapter.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HabitFooterViewHolder.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HabitViewHolder.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeViewModel.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/model/HabitUI.kt
  presentation/home/src/main/res/layout/item_goal_footer.xml
  presentation/home/src/main/res/layout/item_habit.xml
  presentation/home/src/main/res/layout/item_habit_footer.xml
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/model/MateUI.kt
Labels: enhancement

#108 DEP-258 feat: 습관 삭제 시 상태에 따라 다르게 안내 + 세번째 박수 달성시 애니메이션
  core-design-system/src/main/res/drawable/selector_dialog_confirm_button.xml
  core/src/main/res/layout/fragment_three_days_dialog.xml
  presentation/home/build.gradle
  presentation/home/src/main/java/com/depromeet/threedays/home/MainActivity.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/CompleteHabitDialog.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/DeleteHabitDialog.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HabitAdapter.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HabitFooterViewHolder.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HabitViewHolder.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeViewModel.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/MoreActionModal.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/model/HabitUI.kt
  presentation/home/src/main/res/layout/activity_main.xml
  presentation/home/src/main/res/layout/dialog_complete_habit.xml
  presentation/home/src/main/res/layout/dialog_delete_habit.xml
  presentation/home/src/main/res/layout/fragment_home.xml
  presentation/home/src/main/res/layout/item_habit.xml
  presentation/home/src/main/res/layout/item_habit_footer.xml
  presentation/home/src/main/res/layout/modal_more_action.xml
  presentation/home/src/main/res/raw/lottie_clap.json
  presentation/home/src/main/res/values/strings.xml
Labels: enhancement

#109 DEP-262 feat: 스크린샷 저장 기능 구현 (공유하기 페이지)
  core-design-system/src/main/res/drawable/bg_rect_blue50_r10.xml
  core-design-system/src/main/res/drawable/bg_rect_pink50_r10.xml
  presentation/mate/src/main/AndroidManifest.xml
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateViewModel.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/model/MateUI.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/share/ShareMateActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/share/ShareMateViewModel.kt
  presentation/mate/src/main/res/drawable/ic_image_save.xml
  presentation/mate/src/main/res/drawable/ic_image_save_pressed.xml
  presentation/mate/src/main/res/drawable/ic_instagram_share.png
  presentation/mate/src/main/res/drawable/ic_instagram_share_pressed.png
  presentation/mate/src/main/res/drawable/ic_instagram_share_resized.xml
  presentation/mate/src/main/res/drawable/ic_instagram_share_resized_pressed.xml
  presentation/mate/src/main/res/drawable/selector_instragram_share.xml
  presentation/mate/src/main/res/drawable/selector_save_as_image_button.xml
  presentation/mate/src/main/res/layout/activity_share_mate.xml
  presentation/mate/src/main/res/values/strings.xml
Labels: enhancement

#110 DEP-257 feat: 기기 알림 설정 on/off 관리
  app/src/main/AndroidManifest.xml
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeViewModel.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/NotiGuideBottomSheet.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/dialog/MoreActionModal.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/dialog/NotiGuideBottomSheet.kt
  presentation/home/src/main/java/com/depromeet/threedays/home/home/dialog/NotiRecommendBottomSheet.kt
  presentation/home/src/main/res/layout/bottom_sheet_noti_guide.xml
Labels: enhancement

#111 DEP-293 feat: DataStore 구현
  data/src/main/java/com/depromeet/threedays/data/datasource/datastore/DataStoreDataSource.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/datastore/DataStoreDataSourceImpl.kt
  data/src/main/java/com/depromeet/threedays/data/di/LocalModule.kt
  data/src/main/java/com/depromeet/threedays/data/di/RepositoryModule.kt
  data/src/main/java/com/depromeet/threedays/data/repository/NotificationPermissionRepositoryImpl.kt
  dependencies.gradle
  domain/src/main/java/com/depromeet/threedays/domain/repository/NotificationPermissionRepository.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/notification_permission/ReadNotificationPermissionUseCase.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/notification_permission/WriteNotificationPermissionUseCase.kt
Labels: enhancement

#115 DEP-238 feat: 나의 기록 기능 구현
  data/src/main/java/com/depromeet/threedays/data/api/RecordService.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/record/RecordRemoteDataSource.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/record/RecordRemoteDataSourceImpl.kt
  data/src/main/java/com/depromeet/threedays/data/di/RemoteModule.kt
  data/src/main/java/com/depromeet/threedays/data/di/RepositoryModule.kt
  data/src/main/java/com/depromeet/threedays/data/di/ServiceModule.kt
  data/src/main/java/com/depromeet/threedays/data/entity/record/FrequentHabitEntity.kt
  data/src/main/java/com/depromeet/threedays/data/entity/record/RecordEntity.kt
  data/src/main/java/com/depromeet/threedays/data/repository/RecordRepositoryImpl.kt
  domain/src/main/java/com/depromeet/threedays/domain/entity/record/FrequentHabit.kt
  domain/src/main/java/com/depromeet/threedays/domain/entity/record/Record.kt
  domain/src/main/java/com/depromeet/threedays/domain/repository/RecordRepository.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/record/GetRecordUseCase.kt
  domain/src/main/java/com/depromeet/threedays/domain/util/GetStringFromDateTime.kt
  presentation/history/src/main/java/com/depromeet/threedays/history/HabitAdapter.kt
  presentation/history/src/main/java/com/depromeet/threedays/history/HabitViewHolder.kt
  presentation/history/src/main/java/com/depromeet/threedays/history/HistoryFragment.kt
  presentation/history/src/main/java/com/depromeet/threedays/history/HistoryViewModel.kt
  presentation/history/src/main/java/com/depromeet/threedays/history/model/FrequentHabitUI.kt
  presentation/history/src/main/java/com/depromeet/threedays/history/model/RecordUI.kt
  presentation/history/src/main/res/layout/fragment_history.xml
  presentation/history/src/main/res/layout/item_habit.xml
  presentation/history/src/main/res/layout/item_habit_record.xml
  presentation/history/src/main/res/values/strings.xml
Labels: enhancement

#119 DEP-256 feat: 첫 방문 여부에 따라 스플래시 이후 온보딩 띄우는 기능 구현
  data/src/main/java/com/depromeet/threedays/data/di/RepositoryModule.kt
  data/src/main/java/com/depromeet/threedays/data/repository/OnboardingRepositoryImpl.kt
  domain/src/main/java/com/depromeet/threedays/domain/repository/OnboardingRepository.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/onboarding/ReadOnboardingUseCase.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/onboarding/WriteOnboardingUseCase.kt
  navigator/src/main/java/com/depromeet/threedays/navigator/OnboardingNavigator.kt
  presentation/onboarding/build.gradle
  presentation/onboarding/src/main/java/com/depromeet/threedays/onboarding/OnboardingActivity.kt
  presentation/onboarding/src/main/java/com/depromeet/threedays/onboarding/OnboardingFragment.kt
  presentation/onboarding/src/main/java/com/depromeet/threedays/onboarding/OnboardingModule.kt
  presentation/onboarding/src/main/java/com/depromeet/threedays/onboarding/OnboardingNavigatorImpl.kt
  presentation/onboarding/src/main/java/com/depromeet/threedays/onboarding/OnboardingViewModel.kt
  presentation/onboarding/src/main/res/drawable/on_boarding_after_splash_1.png
  presentation/onboarding/src/main/res/drawable/on_boarding_after_splash_2.png
  presentation/onboarding/src/main/res/drawable/on_boarding_after_splash_3.png
  presentation/onboarding/src/main/res/layout/fragment_onboarding.xml
  presentation/splash/src/main/java/com/depromeet/threedays/splash/SplashActivity.kt
  presentation/splash/src/main/java/com/depromeet/threedays/splash/SplashViewModel.kt
Labels: enhancement

#120 DEP-261 feat: 첫 방문 여부에 따라 짝꿍 온보딩 보여주기
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateViewModel.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/onboarding/OnBoardingAdapter.kt
  presentation/mate/src/main/res/drawable/on_boarding_mate_1.png
  presentation/mate/src/main/res/drawable/on_boarding_mate_2.png
  presentation/mate/src/main/res/drawable/on_boarding_mate_3.png
  presentation/onboarding/src/main/java/com/depromeet/threedays/onboarding/OnboardingActivity.kt
Labels: enhancement

#121 Dep-265 feat: 짝꿍 만들기 때 상태에 따라 다른 이미지를 보여주도록 구현
  presentation/mate/build.gradle
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateViewModel.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitAdapter.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitViewHolder.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitViewModel.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/model/HabitUI.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step2/ChooseMateTypeActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step2/ChooseMateTypeViewModel.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameViewMoodel.kt
  presentation/mate/src/main/res/drawable/bg_box_mate_carrot_blue.png
  presentation/mate/src/main/res/drawable/bg_box_mate_carrot_green.png
  presentation/mate/src/main/res/drawable/bg_box_mate_carrot_pink.png
  presentation/mate/src/main/res/drawable/bg_box_mate_completion_carrot_blue.png
  presentation/mate/src/main/res/drawable/bg_box_mate_completion_carrot_green.png
  presentation/mate/src/main/res/drawable/bg_box_mate_completion_carrot_pink.png
  presentation/mate/src/main/res/drawable/bg_box_mate_completion_whip_blue.png
  presentation/mate/src/main/res/drawable/bg_box_mate_completion_whip_green.png
  presentation/mate/src/main/res/drawable/bg_box_mate_completion_whip_pink.png
  presentation/mate/src/main/res/drawable/bg_box_mate_default.png
  presentation/mate/src/main/res/drawable/bg_box_mate_default_blue.png
  presentation/mate/src/main/res/drawable/bg_box_mate_default_green.png
  presentation/mate/src/main/res/drawable/bg_box_mate_default_pink.png
  presentation/mate/src/main/res/drawable/bg_box_mate_whip_blue.png
  presentation/mate/src/main/res/drawable/bg_box_mate_whip_green.png
  presentation/mate/src/main/res/drawable/bg_box_mate_whip_pink.png
  presentation/mate/src/main/res/layout/activity_choose_mate_type.xml
  presentation/mate/src/main/res/layout/activity_connect_habit.xml
  presentation/mate/src/main/res/layout/activity_set_mate_nickname.xml
  presentation/mate/src/main/res/layout/fragment_mate.xml
Labels: enhancement

#122 DEP-215 feat: 짝꿍 만들기 기능 구현
  app/src/main/AndroidManifest.xml
  data/src/main/java/com/depromeet/threedays/data/api/MateService.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/mate/MateRemoteDataSource.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/mate/MateRemoteDataSourceImpl.kt
  data/src/main/java/com/depromeet/threedays/data/entity/mate/PostMateRequest.kt
  data/src/main/java/com/depromeet/threedays/data/repository/MateRepositoryImpl.kt
  domain/src/main/java/com/depromeet/threedays/domain/entity/mate/CreateMate.kt
  domain/src/main/java/com/depromeet/threedays/domain/repository/MateRepository.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/mate/CreateMateUseCase.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step2/ChooseMateTypeActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameViewModel.kt
Labels: enhancement

#123 DEP-265 feat: 짝꿍 팝업 띄워 보기 기능 구현
  core-design-system/src/main/res/drawable/bg_mate_level_1.png
  core-design-system/src/main/res/drawable/bg_mate_level_2.png
  core-design-system/src/main/res/drawable/bg_mate_level_3.png
  core-design-system/src/main/res/drawable/bg_mate_level_4.png
  core-design-system/src/main/res/drawable/bg_mate_level_5.png
  core/src/main/java/com/depromeet/threedays/core/util/ThreeDaysOneButtonDialogFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
  presentation/mate/src/main/res/layout/fragment_mate.xml
  presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitActivity.kt
  presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/archived_mate/ArchivedMateUI.kt
Labels: enhancement

#124 DEP-264 feat: 짝꿍 삭제 기능 구현
  core-design-system/src/main/res/drawable/ic_tab_mate_selected.xml
  core-design-system/src/main/res/drawable/ic_tab_mate_unselected.xml
  data/src/main/java/com/depromeet/threedays/data/api/MateService.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/mate/MateRemoteDataSource.kt
  data/src/main/java/com/depromeet/threedays/data/datasource/mate/MateRemoteDataSourceImpl.kt
  data/src/main/java/com/depromeet/threedays/data/repository/MateRepositoryImpl.kt
  domain/src/main/java/com/depromeet/threedays/domain/repository/MateRepository.kt
  domain/src/main/java/com/depromeet/threedays/domain/usecase/mate/DeleteMateUseCase.kt
  presentation/home/src/main/res/layout/activity_main.xml
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateViewModel.kt
  presentation/mate/src/main/res/values/strings.xml
Labels: enhancement

#133 DEP-260 feat: 짝꿍 페이지 기능 구현 (레벨 보기)
  presentation/mate/src/main/java/com/depromeet/threedays/mate/ClapAdapter.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/ClapViewHolder.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateViewModel.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/model/StampUI.kt
  presentation/mate/src/main/res/drawable/bg_oval_gray.xml
  presentation/mate/src/main/res/drawable/bg_oval_hand_blue.xml
  presentation/mate/src/main/res/drawable/bg_oval_hand_gray.xml
  presentation/mate/src/main/res/drawable/bg_oval_hand_green.xml
  presentation/mate/src/main/res/drawable/bg_oval_hand_pink.xml
  presentation/mate/src/main/res/drawable/ic_hand_gray.xml
  presentation/mate/src/main/res/drawable/ic_hand_white.xml
  presentation/mate/src/main/res/layout/fragment_mate.xml
  presentation/mate/src/main/res/layout/item_clap.xml
  presentation/mate/src/main/res/values/strings.xml
Labels: enhancement

#134 fix: 가장 많이 실천한 습관이 뜨지 않는 버그 수정
  data/src/main/java/com/depromeet/threedays/data/entity/record/FrequentHabitEntity.kt
  data/src/main/java/com/depromeet/threedays/data/entity/record/RecordEntity.kt
Labels: enhancement

#135 DEP-320 fix: 캐릭터가 중첩되어 보이는 버그 수정
  presentation/mate/src/main/res/layout/fragment_mate.xml
Labels: bug

#137 DEP-321 fix: 공유하기에서 습관 캐릭터가 뜨지 않는 버그 수정
  presentation/mate/src/main/java/com/depromeet/threedays/mate/share/ShareMateActivity.kt
  presentation/mate/src/main/res/drawable/ic_logo_white.xml
  presentation/mate/src/main/res/layout/activity_share_mate.xml
Labels: bug

#138 DEP-322 fix: 습관이 없을 때 툴바가 가려지도록 수정
  presentation/history/src/main/java/com/depromeet/threedays/history/HistoryFragment.kt
  presentation/history/src/main/res/layout/fragment_history.xml
Labels: enhancement

#139 DEP-323 fix: 온보딩 (스플래시 이후) 버튼 텍스트가 이상한 문제 해결
  presentation/onboarding/src/main/java/com/depromeet/threedays/onboarding/OnboardingActivity.kt
Labels: bug

#140 DEP-325 fix: 짝꿍 온보딩 모달이 여러개 뜨는 버그 수정
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateViewModel.kt
Labels: bug

#141 DEP-324 fix: 내 기록에서 습관 만들고 왔을때 화면 변화 없는 버그 수정
  presentation/history/src/main/java/com/depromeet/threedays/history/HistoryFragment.kt
  presentation/history/src/main/java/com/depromeet/threedays/history/HistoryViewModel.kt
Labels: bug

#149 fix: 버튼에 들어간 쉐도우 일괄삭제
  presentation/history/src/main/res/layout/fragment_history.xml
  presentation/home/src/main/res/layout/bottom_sheet_noti_recommend.xml
  presentation/mate/src/main/res/layout/activity_choose_mate_type.xml
  presentation/mate/src/main/res/layout/activity_connect_habit.xml
  presentation/mate/src/main/res/layout/bottom_sheet_mate_on_boarding.xml
  presentation/mate/src/main/res/layout/fragment_mate.xml
  presentation/mypage/src/main/res/layout/activity_archived_habit.xml
  presentation/mypage/src/main/res/layout/fragment_edit_nickname_dialog.xml
  presentation/onboarding/src/main/res/layout/activity_onboarding.xml
Labels: bug

#150 DEP-329 fix: 짝꿍 생성시 습관 선택이 제대로 되지 않는 버그 수정
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitAdapter.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitViewHolder.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitViewModel.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/model/HabitUI.kt
  presentation/mate/src/main/res/drawable/selector_gray_100_r_10_gray_200_r_10.xml
  presentation/mate/src/main/res/layout/item_connect_habit.xml
Labels: bug

#151 fix: 짝꿍 만들기 뒤로가기시 단계 하나만 나가지도록 수정
  app/src/main/AndroidManifest.xml
  presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameActivity.kt
Labels: bug

#152 DEP-331 fix: 나의 기록 이동 가능한 범위 만큼만 이동하도록 수정
  domain/src/main/java/com/depromeet/threedays/domain/util/GetDateTimeFromString.kt
  presentation/history/src/main/java/com/depromeet/threedays/history/HistoryFragment.kt
  presentation/history/src/main/java/com/depromeet/threedays/history/HistoryViewModel.kt
  presentation/history/src/main/res/layout/fragment_history.xml
Labels: bug, enhancement

#153 DEP-332 bugfix: 가장 많이 실천한 습관 위치 조정, 쉐도우 추가
  presentation/history/src/main/res/drawable/ic_emoji_shadow.png
  presentation/history/src/main/res/layout/fragment_history.xml
Labels: bug

#154 DEP-328 fix: 네비게이션 홈 아이콘 변경
  core-design-system/src/main/res/drawable/ic_tab_home_selected.xml
  core-design-system/src/main/res/drawable/ic_tab_home_unselected.xml
Labels: bug

#155 DEP-333 fix: 짝꿍 없는 상태에서 툴바쪽 아이콘 일부 없애기
  presentation/mate/src/main/res/layout/fragment_mate.xml
Labels: bug

#156 DEP-334 fix: 짝꿍 만들기 단계에서 전환 애니메이션 없애기
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step2/ChooseMateTypeActivity.kt
  presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameActivity.kt
Labels: enhancement

#158 DEP-263 feat: 인스타 스토리 공유하기 기능 구현
  dependencies.gradle
  presentation/mate/build.gradle
  presentation/mate/src/main/java/com/depromeet/threedays/mate/share/ShareMateActivity.kt
  presentation/mate/src/main/res/layout/activity_share_mate.xml
Labels: enhancement
